server:
  port: 8089
spring:
  application:
    name: cart-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:  #设置心跳反应时间  在注册服务完成以后，服务提供者会维持一个心跳（定时向EurekaServer发起Rest请求）,告诉EurekaServer我还活着
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
leyou:
  jwt:
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: token # cookie的名称