server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: false
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
    search-service: /search/** # 将商品微服务映射到/search/**
    user-service: /user/** # 将商品微服务映射到/user/**
    auth-service: /auth/** # 授权中心微服务
    sms-service: /sms/** #短信微服务
    cart-service: /cart/**  #购物车微服务
  host:
    socket-timeout-millis: 60000 #创建socket链接超时时间
    connect-timeout-millis: 60000 #链接超时时间
  add-host-header: true  #携带请求头信息
  sensitive-headers: #禁止使用的头信息
ribbon:
  ConnectTimeout: 60000 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
leyou:
  jwt:
    pubKeyPath:  C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: token # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/user/send
      - /api/item